### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by riccardomurri**
This is work in progress porting to Py3, see issue #264 for details.

### CODE REVIEW

**Comment by riccardomurri** [comment]
Good news! With the latest additions, all test pass with Python2 after code modernization.

**Comment by riccardomurri** [comment]
All tests pass on Python 2.7, 3.5, 3.6, 3.7.

**Comment by smaffiol** [comment]
$gsession list
gets me this:
gsession: [2019-08-19 15:01:04] WARNING : Ignoring error from loading 'QTLApplication.29': Failed loading object QTLApplication.29 from file(s) [u'/home/ubuntu/qtl/snp_Median_tci_FixedTP_session/jobs/QTLApplication.29', u'/home/ubuntu/qtl/snp_Median_tci_FixedTP_session/jobs/QTLApplication.29.OLD']. (Earlier log lines may provide more details.)
gsession: [2019-08-19 15:01:04] WARNING : Failed loading file '/home/ubuntu/qtl/snp_Median_tci_FixedTP_session/jobs/QTLApplication.23': AttributeError: 'UrlKeyDict' object has no attribute '_force_abs'
Traceback (most recent call last):
  File "/home/ubuntu/gc3pie_p2.7/src/gc3libs/persistence/filesystem.py", line 126, in load
    obj = self._load_from_file(source)
  File "/home/ubuntu/gc3pie_p2.7/src/gc3libs/persistence/filesystem.py", line 104, in _load_from_file
    obj = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1204, in load_setitem
    dict[key] = value
  File "/home/ubuntu/gc3pie_p2.7/src/gc3libs/url.py", line 502, in __setitem__
    dict.__setitem__(self, Url(key, self._force_abs), value)
AttributeError: 'UrlKeyDict' object has no attribute '_force_abs'

on a python2.7

**Comment by riccardomurri** [comment]
@malmstroem @smaffiol This "AttributeError:  'UrlKeyDict' object has no attribute '_force_abs'" should be fixed in the latest commit in this "python3" branch.  Can you please test again?

**Comment by smaffiol** [comment]
After update f12ed03fcbb2ad2e66434e19b21745bd1cb92fdb 
* UrlKeyDict error is resolved
$ ginfo -s ./snp_Median_tci_FixedTP_session/ QTLApplication.46 -vvv
...
ginfo: [2019-08-20 11:34:39] CRITICAL: TypeError: unicode argument expected, got 'str'                                                                                                                                                                                                    Traceback (most recent call last):                                                                                                                                                                                                                                                          File "/home/ubuntu/gc3pie_p2.7/src/gc3libs/cmdline.py", line 527, in run                                                                                                                                                                                                                    return super(_Script, self).run()                                                                                                                                                                                                                                                       File "/home/ubuntu/gc3pie_p2.7/local/lib/python2.7/site-packages/cli/app.py", line 245, in run                                                                                                                                                                                              return self.post_run(returned)                                                                                                                                                                                                                                                          File "/home/ubuntu/gc3pie_p2.7/local/lib/python2.7/site-packages/cli/app.py", line 241, in run                                                                                                                                                                                              returned = self.main(*args)                                                                                                                                                                                                                                                             File "/home/ubuntu/gc3pie_p2.7/src/gc3utils/commands.py", line 482, in main                                                                                                                                                                                                                 only_keys=only_keys)                                                                                                                                                                                                                                                                    File "/home/ubuntu/gc3pie_p2.7/src/gc3libs/utils.py", line 1455, in prettyprint                                                                                                                                                                                                             only_keys, sstream, full_name + '.', _exclude)                                                                                                                                                                                                                                          File "/home/ubuntu/gc3pie_p2.7/src/gc3libs/utils.py", line 1489, in prettyprint                                                                                                                                                                                                             output.write(second)                                                                                                                                                                                                                                                                  TypeError: unicode argument expected, got 'str'

**Comment by riccardomurri** [comment]
@smaffiol "TypeError: unicode argument expected, got 'str'" should be fixed in the latest commit dfcc00c2 -- can you please try again?

Note that you won't be able to read sessions created before commit f12ed03; they will fail with this error:

```
Traceback (most recent call last):
  File "/home/rmurri/w/gc3pie/gc3libs/persistence/filesystem.py", line 126, in load
    obj = self._load_from_file(source)
  File "/home/rmurri/w/gc3pie/gc3libs/persistence/filesystem.py", line 104, in _load_from_file
    obj = unpickler.load()
AttributeError: 'UrlKeyDict' object has no attribute '__dict__'
```

(This backwards incompatibility is expected; might be a reason to bump the version number to 3.0 instead of 2.6.)

**Comment by malmstroem** [comment]
It is working for me, thanks for the update!

**Comment by smaffiol** [comment]
After update dfcc00c2a2429742bd2709cf8217a508d3f11fe6
TypeError: unicode argument expected, got 'str' is solved.
but I noticed the following (which probably was there already):
$ gsession list -r ./snp_Median_tci_FixedTP_session
+-------------------+--------------------------+------------+-----------------------------------------------------------------------------------------------------+
| JobID             | Job name                 | State      | Info                                                                                                |
+-------------------+--------------------------+------------+-----------------------------------------------------------------------------------------------------+
| QTLApplication.75 | CyclinB_iPI3K_60_batch_0 | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:36:26 2019 |
+-------------------+--------------------------+------------+-----------------------------------------------------------------------------------------------------+

while:
$ ll ./snp_Median_tci_FixedTP_session/jobs/
total 128
drwxrwxr-x 2 ubuntu ubuntu 4096 Aug 20 11:37 ./
drwxrwxr-x 3 ubuntu ubuntu 4096 Aug 20 11:37 ../
-rw-rw-r-- 1 ubuntu ubuntu 5057 Aug 20 11:36 QTLApplication.61
-rw-rw-r-- 1 ubuntu ubuntu 4693 Aug 20 11:36 QTLApplication.62
-rw-rw-r-- 1 ubuntu ubuntu 5797 Aug 20 11:37 QTLApplication.63
-rw-rw-r-- 1 ubuntu ubuntu 4697 Aug 20 11:35 QTLApplication.64
-rw-rw-r-- 1 ubuntu ubuntu 5065 Aug 20 11:36 QTLApplication.65
-rw-rw-r-- 1 ubuntu ubuntu 4705 Aug 20 11:36 QTLApplication.66
-rw-rw-r-- 1 ubuntu ubuntu 4733 Aug 20 11:35 QTLApplication.67
-rw-rw-r-- 1 ubuntu ubuntu 5073 Aug 20 11:36 QTLApplication.68
-rw-rw-r-- 1 ubuntu ubuntu 4729 Aug 20 11:36 QTLApplication.69
-rw-rw-r-- 1 ubuntu ubuntu 4717 Aug 20 11:36 QTLApplication.70
-rw-rw-r-- 1 ubuntu ubuntu 4709 Aug 20 11:36 QTLApplication.71
-rw-rw-r-- 1 ubuntu ubuntu 4725 Aug 20 11:36 QTLApplication.72
-rw-rw-r-- 1 ubuntu ubuntu 5061 Aug 20 11:36 QTLApplication.73
-rw-rw-r-- 1 ubuntu ubuntu 4737 Aug 20 11:36 QTLApplication.74
-rw-rw-r-- 1 ubuntu ubuntu 4683 Aug 20 11:36 QTLApplication.75

and:
$ gstat -s ./snp_Median_tci_FixedTP_session
+-------------------+--------------------------------+------------+-----------------------------------------------------------------------------------------------------+
| JobID             | Job name                       | State      | Info                                                                                                |
+-------------------+--------------------------------+------------+-----------------------------------------------------------------------------------------------------+
| QTLApplication.61 | p-p53_EGF_0_batch_0            | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:36:56 2019 |
| QTLApplication.62 | GAPDH_EGF_0_batch_0            | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:36:16 2019 |
| QTLApplication.63 | cleavedCas_EGF_0_batch_0       | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:37:06 2019 |
| QTLApplication.64 | p-MKK4_EGF_0_batch_0           | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:35:55 2019 |
| QTLApplication.65 | p-ERK_iMEK_60_batch_0          | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:36:46 2019 |
| QTLApplication.66 | p-MKK4_iMEK_60_batch_0         | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:36:36 2019 |
| QTLApplication.67 | p-Akt(Ser473)_iMEK_60_batch_0  | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:35:55 2019 |
| QTLApplication.68 | p-90RSK_iMEK_60_batch_0        | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:36:46 2019 |
| QTLApplication.69 | p-MKK3-MKK6_iPI3K_60_batch_0   | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:36:16 2019 |
| QTLApplication.70 | p-p90RSK_iPI3K_60_batch_0      | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:36:05 2019 |
| QTLApplication.71 | p-MKK4_iPI3K_60_batch_0        | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:36:05 2019 |
| QTLApplication.72 | p-MAPKAPK2_iPI3K_60_batch_0    | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:36:36 2019 |
| QTLApplication.73 | IdU_iPI3K_60_batch_0           | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:36:56 2019 |
| QTLApplication.74 | p-AKT(Thr308)_iPI3K_60_batch_0 | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:36:26 2019 |
| QTLApplication.75 | CyclinB_iPI3K_60_batch_0       | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Tue Aug 20 11:36:26 2019 |
+-------------------+--------------------------------+------------+-----------------------------------------------------------------------------------------------------+

**Comment by riccardomurri** [comment]
@smaffiol I'm not sure what is wrong in the output of commands you posted?

**Comment by smaffiol** [comment]
ah, here it is with the sequence of the commands to run:
$ gsession list ./snp_Median_tci_FixedTP_session_20190822
$ ginfo -s ./snp_Median_tci_FixedTP_session_20190822  QTLApplication.89
$ gsession list ./snp_Median_tci_FixedTP_session_20190822

with this order, the last `gsession` command only prints out the info of the job `QTLApplication.89`
$ gsession list ./snp_Median_tci_FixedTP_session_20190822
+-------------------+--------------------------------+------------+-----------------------------------------------------------------------------------------------------+
| JobID             | Job name                       | State      | Info                                                                                                |
+-------------------+--------------------------------+------------+-----------------------------------------------------------------------------------------------------+
| QTLApplication.89 | p-AKT(Thr308)_iPI3K_60_batch_0 | TERMINATED | Transition from state TERMINATING to state TERMINATED (returncode: 256) at Thu Aug 22 07:17:03 2019 |
+-------------------+--------------------------------+------------+-----------------------------------------------------------------------------------------------------+

**Comment by riccardomurri** [comment]
I am going to rebase this against "master" and then force-push before merging.

**Comment by riccardomurri** [comment]
... aaaaaaaand we're go!

**Pull request merged**
